name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

       
jobs:
  build:
    strategy:
      matrix:
        go-version: [1.15.x, 1.16.x, 1.17.x,]
        os: [ubuntu-latest, macos-latest, windows-latest]        
    env:
      CGO_ENABLED: 0
    runs-on: ${{ matrix.os }}
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2      
      with:
        go-version: ${{ matrix.go-version }}

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Vet
      run: go vet ./...

    - name: Test
      run: go test ./...

    - name: Test Race
      env:
        CGO_ENABLED: 1
      run: go test -cpu="1,4" -short -race -v ./...
      
  build-special:
    env:
      CGO_ENABLED: 0
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2      
      with:
        go-version: 1.17.x

    - name: Checkout code
      uses: actions/checkout@v2

    - name: fmt
      run: diff <(gofmt -d .) <(printf "")

    - name: Test 386
      run: GOOS=linux GOARCH=386 go test ./...

    - name: goreleaser deprecation
      run: curl -sfL https://git.io/goreleaser | VERSION=v1.4.1 sh -s -- check
      
    - name: goreleaser snapshot
      run: curl -sL https://git.io/goreleaser | VERSION=v1.4.1 sh -s -- --snapshot --skip-publish --rm-dist

